name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./bin

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./bin

      - name: List files in ./bin
        run: ls -l ./bin

      - name: Get latest commit message
        id: commit
        run: |
          echo "::set-output name=message::$(git log --format=%B -n 1)"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          tag_name: ${{ steps.commit.outputs.message }}
          release_name: Version - ${{ steps.commit.outputs.message }}
          draft: false
          prerelease: false

      - name: Upload Release linux x64
        id: upload-release-asset-linux-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ai-bot-x86-linux-x64
          asset_name: ai-bot-x86-linux-x64
          asset_content_type: application/octet-stream

      - name: Upload Release macos x64
        id: upload-release-asset-macos-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ai-bot-x86-macos-x64
          asset_name: ai-bot-x86-macos-x64
          asset_content_type: application/octet-stream

      - name: Upload Release win x64
        id: upload-release-asset-win-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/ai-bot-x86-win-x64.exe
          asset_name: ai-bot-x86-win-x64.exe
          asset_content_type: application/octet-stream
